### ISSUE TITLE
Apps aren't loaded yet error

### ISSUE THREAD

**Issue by jacqueline-chan** [UTMediaCAT/Voyage#102]
Traceback (most recent call last):
  File "article_explorer.py", line 44, in <module>
    from articles.models import*
  File "/voyage_storage_jacqueline/Voyage/Frontend/articles/models.py", line 7, in <module>
    class Article(models.Model):
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/django/db/models/base.py", line 110, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/django/apps/registry.py", line 247, in get_containing_app_config
    self.check_apps_ready()
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/django/apps/registry.py", line 125, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by jacqueline-chan** [comment]
Leads:

https://stackoverflow.com/questions/34114427/django-upgrading-to-1-9-error-appregistrynotready-apps-arent-loaded-yet
