### ISSUE TITLE
**python3 manage.py runserver 0.0.0.0:80**  returns an error as below and this prevents the server from running

### ISSUE THREAD

**Issue by jacqueline-chan** [UTMediaCAT/Voyage#97]
**python3 manage.py runserver 0.0.0.0:80**  returns an error as below and this prevents the server from running

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.pyenv/versions/mediacatProjectDjangoUpgrade/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/root/.pyenv/versions/mediacatProjectDjangoUpgrade/lib/python3.5/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/root/.pyenv/versions/mediacatProjectDjangoUpgrade/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/root/.pyenv/versions/mediacatProjectDjangoUpgrade/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/root/.pyenv/versions/mediacatProjectDjangoUpgrade/lib/python3.5/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/root/.pyenv/versions/3.5.2/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/voyage_storage_with_django_upgrade/Voyage/Frontend/Frontend/settings.py", line 13, in <module>
    from django.conf.global_settings import TEMPLATE_CONTEXT_PROCESSORS as TCP
ImportError: cannot import name 'TEMPLATE_CONTEXT_PROCESSORS'

**Comment by amygao9** [comment]
'TEMPLATE_CONTEXT_PROCESSORS' is no longer supported in django 1.10, changed settings.py to include templates format to import TCP instead. This error appears to be resolved with this fix

**Comment by amygao9** [comment]
Deleted previous 'TEMPLATE_CONTEXT_PROCESSORS' imports and included new templates configuration: TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors'
            ],
        },
    },
]
