### ISSUE TITLE
python3 manage.py runserver AttributeError

### ISSUE THREAD

**Issue by amygao9** [UTMediaCAT/Voyage#98]
python3 manage.py runserver 0.0.0.0:80 
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fb20388e378>
Traceback (most recent call last):
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    autoreload.raise_last_exception()
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/root/.pyenv/versions/3.5.2/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/voyage_storage_jacqueline/Voyage/Frontend/explorer/models.py", line 40, in <module>
    class ReferringSite(models.Model):
  File "/voyage_storage_jacqueline/Voyage/Frontend/explorer/models.py", line 50, in ReferringSite
    tags = TaggableManager()
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/taggit/managers.py", line 285, in __init__
    rel = TaggableRel(self, related_name, self.through, to=to)
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/taggit/managers.py", line 55, in __init__
    self.to = to
AttributeError: can't set attribute

**Comment by amygao9** [comment]
Server does not run - Could be due to unsupported version of taggit

**Comment by amygao9** [comment]
Resolved - upgraded django taggit to 0.23.0
