### ISSUE TITLE
manage.py runserver Import error

### ISSUE THREAD

**Issue by amygao9** [UTMediaCAT/Voyage#99]
python3 manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7faeb56ad488>
Traceback (most recent call last):
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.pyenv/versions/jacqueline/lib/python3.5/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/root/.pyenv/versions/3.5.2/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/voyage_storage_jacqueline/Voyage/Frontend/Frontend/urls.py", line 1, in <module>
    from django.conf.urls import patterns, include, url
ImportError: cannot import name 'patterns'

**Comment by amygao9** [comment]
Patterns was depreciated in django 1.9. Now use a list to store url patterns and remove import patterns.

**Comment by amygao9** [comment]
Same error in all the urls.py files in articles, explorer, home, statistics, tweets, visualizations. Fixed all of them by removing import statement and using lists to store urls.
